services:
  rooster:
    image: ikke1992/rooster:latest
    container_name: rooster
    depends_on:
      - postgresdb
    restart: on-failure
    env_file: ./.env
    ports:
      - 4201:5080
      - 5500:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_FRONTEND_URL=$FRONTEND_URL:$ANGULAR_LOCAL_PORT      
      - APP_BACKEND_URL=$BACKEND_URL:$SPRING_LOCAL_PORT

  postgresdb:
    image: postgres
    container_name: rooster_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
      
      